[profile.default]
libs = ["lib"]
out = "out"
remappings = ["@solmate=lib/solmate"]
solc = "0.8.20"
src = "src"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
